### ISSUE TITLE
Mapping of Typscript Source Files

### ISSUE THREAD

**Issue by dwgray** [lathonez/clicker#142]
I'm using your instructions for debugging clicker app using npm run karma, choosing the debug tab in chrome, etc.

Everything works great, except that the application source files don't get mapped back to the original.  I'm seeing something like the attached (which even though it says it's a .ts file and that chrome says that its mapping from the .browserfy file, it's obviously not the original source.  Is this expected?  If not, any thoughts on what might I be doing with the environment to lose the mapping?  If so, how do you debug the actual app source?

[app.ts.txt](https://github.com/lathonez/clicker/files/460102/app.ts.txt)

Note that the .spec.ts files appear to be mapped.  Is this some double compiler issue perhaps?

**Comment by lathonez** [comment]
see #119 and #121 

I have noticed this myself, I think the transform crept back in to the debug run, possibly removed in #140

**Comment by lathonez** [comment]
This is working for me _now_:

![screenshot-20160908093329-807x576](https://cloud.githubusercontent.com/assets/7236936/18332135/833bc094-75a7-11e6-8653-8349231f593e.png)

Though I think it's only since #140, so in 1.13.1. Do you have the fix in #140 / what [version](https://github.com/lathonez/clicker/blob/master/package.json#L59) is in your `package.json`?

**Comment by dwgray** [comment]
My apologies, I didn't sync before submitting this (in my defense, I had just pulled down the project yesterday).  Works great with version 1.13.1.  Thanks!

**Comment by lathonez** [comment]
No worries, it's been broken for a while just a coincidence that it was fixed since you pulled in.
