### ISSUE TITLE
Dynamic Theming

### ISSUE THREAD

**Issue by codestellar** [lathonez/clicker#145]
This is really an awesome work done. Thank you lathonez. I am wondering if you can add dynamic theming feature as well. Just a thought.

**Comment by lathonez** [comment]
@codestellar Thanks.

Dynamic theming sounds interesting. What exactly do you have in mind?

**Comment by codestellar** [comment]
Since this is a very nice boilerplate, I was thinking if we could have skins as well which will change the color of all the buttons/menu etc. A user can select a color as per his choice.

**Comment by lathonez** [comment]
Ionic 2 comes loaded with a powerful theme setup. Josh Moronoy has a good blog post on the subject: http://www.joshmorony.com/a-guide-to-styling-an-ionic-2-application/

It uses SASS which compiles into CSS _at build time_. This allows you to do things like change primary / secondary colours (or [any other scss variables](http://ionicframework.com/docs/v2/theming/overriding-ionic-variables/) with ease at build time.

Unfortunately the situation at runtime is very different. By trying to override the compiled CSS dynamically, we lose the power of the SASS variables to apply the changes to all relevant aspects of our app.

For example, we may find the CSS to change the primary colour for a button, but this is very different from the CSS which we'll need to change the primary colour for, say, a checkbox.

Instead of changing one variable we need to override many css classes to make a simple colour change. If Ionic at some point change a class name, a lot of our work could be instantly broken

There are the following approaches to dynamic styling an Ionic 2 app:

* Use SASS templates to compile multiple css stylesheets at build time. For example, one with a primary colour of yellow, one of red. When the user wants to change the style, swap the stylesheets.
* Programmatically (or otherwise) find the relevant compiled css rules for the specific change you want to make. For example, Ionic has 2000-3000 css rules which are compiled from sass. If you know that the primary colour is yellow, you can search through all those rules to find which one have yellow applied, and switch them to red.
* Develop your own css rules to overwrite Ionics and switch them (as we would typically when thinking about dynamic theming an app).

I have used the second method above with some success in a closed source project. It is a long way from ideal. My preferred solution would be the first, as we're just extending the current solution at build time to provide multiple _static_ themes, each of which can be applied dynamically.

I will keep this open and add it to the roadmap, but as you may appreciate from the above dynamic styling in Ionic 2 doesn't appear to be trivial. If you come along any resources which provide better solutions then those outlined above, please share them here.

**Comment by lathonez** [comment]
This should really be raised with Ionic
