### ISSUE TITLE
commit or not commit typings?

### ISSUE THREAD

**Issue by BugsBunnyBR** [lathonez/clicker#18]
The ionic team seems to be commiting in [their](https://github.com/BugsBunnyBR/ionic2-app-base/tree/typescript)  repos...

**Comment by lathonez** [comment]
I'd sooner follow [Angular 2 Seed](https://github.com/mgechev/angular2-seed/blob/master/package.json#L21) to be honest.

For me it doesn't make any sense to keep Typings in our own VC. If we want to change them they should be forked and pushed back to typings, if not we shouldn't have them under VC?

On that note though I will make a task to have a look at where Angular 2 Seed has gone since I forked from it ages ago and pull in any cool stuff they have.

**Comment by BugsBunnyBR** [comment]
ok, no typings in the repo.
