### ISSUE TITLE
Guide or mini tutorial about how to build for an specific environment

### ISSUE THREAD

**Issue by SoldierCorp** [lathonez/clicker#217]
I just saw that a PR was applied and it's related to the builds for each environment but I cannot understand the way to setup this and I really appreciate if you can tell me how to do this please.

Also because you have an environments folder but I don't know how to use it or if are related to the #135 

Thanks!

**Comment by lathonez** [comment]
Since Ionic have moved from Gulp to Webpack, #135 is obsolete. I will remove it in favour of: https://github.com/driftyco/ionic-cli/issues/1205

This repo isn't Ionic - it's a starter / seed project for setting up unit testing. I suggest contributing to the upstream issue above, some users have provided their solutions for environment builds.

**Comment by lathonez** [comment]
5a3e177
