### ISSUE TITLE
Continuous Integration with VSTS

### ISSUE THREAD

**Issue by Killmore** [lathonez/clicker#218]
Having an issue when I run my tests in VSTS that contain calls to the TestUtils. Below is the code to my unit test. Running it in my CI build results in: 
**Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL** 

If I comment out the beforeEach method, it works so I'm assuming it has something to do with the async aspect. 

```javascript
describe('Pages: Login', () => {  
  beforeEach(async(() => TestUtils.beforeEachCompiler([LoginPage]).then(compiled => {
    fixture = compiled.fixture;
    instance = compiled.instance;    
  })));

  afterEach(() => {    
    fixture.destroy();    
  });
      
  it('works when beforeEach method commented out', () => {
    expect(true).toBeTruthy();    
  })  
});
```

Funny thing is it works when I run it locally but once I push up to the server and CI build kicks off it don't likey... Any thoughts?

**Comment by lathonez** [comment]
I have zero experience with VSTS.

Drawing from wider CI experience (Jenkins / Travis), most all my problems where something works locally but doesn't on CI have been due to version mismatches. Typically my local machine has a version of something I don't expect.

My suggestions are:

* totally wipe the project from your machine, re-clone / install it
* try the tests on a different machine
* try the tests using travis (you should be able to use my travis.yml pretty much verbatim)
* you could also try on appveyor (ditto my appveyor.yml)

Further to that I'd be raising this with the VSTS community.

Sorry I can't be of more help - I'd hope that the fact we use two CI providers here will let you prove out whether or not the issue is with your code or with the VSTS CI setup.

**Comment by lathonez** [comment]
Oh - obviously if you find it's an issue with the framework we're using here please re-open so I can address it.
