### ISSUE TITLE
Test failed – 404: /base/moment.js

### ISSUE THREAD

**Issue by jasonwaters** [lathonez/clicker#33]
Hey there,  I just wanted to say thanks for this repo and the write up!  I've copied your setup in my project, but my test is failing due to karma being unable to find moment.js.  I'm using moment.js in some of my implementation code.

I added moment to the paths map in system.config, as well as to files array in karma.config, but still no dice.

Obviously this isn't an issue with your guide or repository, but I figured you might be able to point me in the right direction?

**Comment by lathonez** [comment]
Hey,

Thanks for reaching out. Moment is a great library! I use it in another
project with this set up just fine.

I'M AFK at the moment, but you need to add it to the files array _and_
proxies in karma.config.js. You don't need to touch system.

There are some links on the FAQ at the bottom of the blog which demonstrate
including other third party libs which might be helpful.

Otherwise I'll get back to you with an example.

Incidentally I'm trying to remove the need to modify karma.config.js at all
for external libs but it's a work in progress.

Let me know how go.

**Comment by lathonez** [comment]
So, to use `moment.js`:

* `npm install --save-dev moment`
* install typings:

```
typings install --ambient --save-dev moment
typings install --ambient --save-dev moment-node
```
* add `moment.js` in `karma.config.js`:

```
x220:~/code/clicker$ git diff test/karma.config.js
diff --git a/test/karma.config.js b/test/karma.config.js
index 42eecc9..23a38cb 100644
--- a/test/karma.config.js
+++ b/test/karma.config.js
@@ -27,6 +27,7 @@ module.exports = function(config) {
       { pattern: 'node_modules/ionic-angular/**/*.js', included: false, watched: false },
       { pattern: 'node_modules/rxjs/**/*.js', included: false, watched: false },
       { pattern: 'www/build/test/**/*.js', included: false, watched: true },
+      { pattern: 'node_modules/moment/moment.js', inclueded: false, watched: false },
 
       'test/test-main.js'
     ],
@@ -68,7 +69,8 @@ module.exports = function(config) {
     proxies: {
       // allows us to keep test code separate from app code and still have the references work
       '/base/node_modules/ionic-angular/decorators/app.js': '/base/www/build/test/app.stub.js', // stub out Ionic's @App decorator
-      '/base/ionic-angular.js': '/base/test/ionic-angular.js'
+      '/base/ionic-angular.js': '/base/test/ionic-angular.js',
+      '/base/moment.js': '/base/node_modules/moment/moment.js'
     },
 
     // level of logging
```

**Comment by jasonwaters** [comment]
wow, thanks a lot, I appreciate your help!
