### ISSUE TITLE
app.spec.ts is not included in the TypeScript compilation context

### ISSUE THREAD

**Issue by BugsBunnyBR** [lathonez/clicker#4]
Man, just a side note cause you already saved the testing in my project...But I have an small issue... I use Atom + atom-typescript as editor + syntax and it gives me this following line when I open  `app.spec.ts` (or any other test file for that matter)
`
The file "/home/bunny/git/clicker/test/app.spec.ts" is not included in the TypeScript compilation context.  If this is not intended, please check the "files" or "filesGlob" section of your tsconfig.json file.at line 1 col 1
`
Would you help me to understand what should be the right approach to get rid of this warning?
I tried 
```
"files": [
    "typings/tsd.d.ts",
    "app/app.ts",
   "test/**/*.ts"
  ],
```
, but it did not made the warning go way.
I also tried 
```
"exclude": [
    "node_modules",
    "test"
  ],
```
but also had no effect.

Thanks

**Comment by lathonez** [comment]
Interesting, I'm using sublime + the official typescript plugin, and it doesn't seem to be bitching at me. However, it should obviously be working well in all the editors.

In the setup here, I've kept the test code (*.spec.ts) totally separate from the app / prod code. You could go another way with this in your own project and keep the spec files together with the app. 

```
app/app.ts
app/app.spec.ts
```

instead of

```
app/app.ts
test/app.spec.ts
```

I read a few forums about this and decided it was cleaner to keep them separate. A lot of people advocate keeping the files together because they are easier to find and people are more likely to keep them up to date. Anyway, if you wanted to restructure and keep them together then obviously you do not have this problem.

But, as we are keeping them separate..

tsconfig.json is being used by webpack to compile the project and build it for prod. It knows nothing about the test files, and we don't really want it to otherwise it will start compile the test code during ionic builds.

The following code is what we use to compile everything including the tests (overwrites tsconfig.json):

https://github.com/lathonez/clicker/blob/master/gulpfile.js#L28-L52

Regarding the warning from Atom

`The file "/home/bunny/git/clicker/test/app.spec.ts" is not included in the TypeScript compilation context. If this is not intended, please check the "files" or "filesGlob" section of your tsconfig.json file.at line 1 col 1`

Thing is, it is totally intended, that's kinda the point of the separation I have. Adding the file to tsconfig.json files list should fix it (maybe see https://github.com/TypeStrong/atom-typescript/issues/681 if it doesn't) but that isn't a good solution as you lose the separation.

If you can't live with the warning and there isn't a way of disabling it in atom, maybe think about restructuring so the spec code lives with the app code?

Or maybe there is a way of defining a separate tsconfig.json for atom to use?

**Comment by lathonez** [comment]
Feel free to reopen if you have further questions / disagree.
