### ISSUE TITLE
Defining a new build process

### ISSUE THREAD

**Issue by galvanu** [lathonez/clicker#61]
Why are we defining a new build process and not taking the ionic build task from the main gulpfile.js?

**Comment by lathonez** [comment]
We do use the ionic build tasks where possible.

The ionic gulpfile is [sourced](https://github.com/lathonez/clicker/blob/master/test/gulpfile.ts#L13-L16) and an [ionic.build](https://github.com/lathonez/clicker/blob/master/test/gulpfile.ts#L118-L124) wrapper task is created. Also the ionic build subtasks are [hooked directly](https://github.com/lathonez/clicker/blob/master/test/gulpfile.ts#L129) from our build task.

Reasons why we need some of our own build tasks:

* Ionic bundles compiled typescript into `app.bundle.js`, we need it as separate files (this is the main thing)
* Ionic doesn't compile `*.spec`
* Ionic doesn't compile `*.e2e`

Since Ionic have recently moved back to gulp it's made it very easy for us to hook into their tasks directly and not duplicate any effort.
